# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_humanuserconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Human')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('recipe', models.TextField()),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Human')),
                ('ingredients', models.ManyToManyField(related_name='meals', to='meals.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_commencing', models.DateField()),
                ('friday_breakfast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_friday_breakfast', to='meals.Meal')),
                ('friday_dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_friday_dinner', to='meals.Meal')),
                ('friday_lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_friday_lunch', to='meals.Meal')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Human')),
                ('monday_breakfast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_monday_breakfast', to='meals.Meal')),
                ('monday_dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_monday_dinner', to='meals.Meal')),
                ('monday_lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_monday_lunch', to='meals.Meal')),
                ('saturday_breakfast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_saturday_breakfast', to='meals.Meal')),
                ('saturday_dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_saturday_dinner', to='meals.Meal')),
                ('saturday_lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_saturday_lunch', to='meals.Meal')),
                ('sunday_breakfast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_sunday_breakfast', to='meals.Meal')),
                ('sunday_dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_sunday_dinner', to='meals.Meal')),
                ('sunday_lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_sunday_lunch', to='meals.Meal')),
                ('thursday_breakfast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_thursday_breakfast', to='meals.Meal')),
                ('thursday_dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_thursday_dinner', to='meals.Meal')),
                ('thursday_lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_thursday_lunch', to='meals.Meal')),
                ('tuesday_breakfast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_tuesday_breakfast', to='meals.Meal')),
                ('tuesday_dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_tuesday_dinner', to='meals.Meal')),
                ('tuesday_lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_tuesday_lunch', to='meals.Meal')),
                ('wednesday_breakfast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_wednesday_breakfast', to='meals.Meal')),
                ('wednesday_dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_wednesday_dinner', to='meals.Meal')),
                ('wednesday_lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_wednesday_lunch', to='meals.Meal')),
            ],
        ),
    ]
