# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_auto_20151212_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='value',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
