# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 15:24
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_auto_20151212_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalisedMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=5, max_digits=10)),
                ('source_name', models.CharField(default=b'manual', max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RouteMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='health.Measurement')),
            ],
        ),
    ]
