# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_normalisedmeasurement_routemeasurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementfor',
            name='human',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Human'),
            preserve_default=False,
        ),
    ]
