# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_human_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('auth_details', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='human',
            name='user',
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Human'),
        ),
    ]
