# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 22:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20151213_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanUserConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_write', models.BooleanField(default=False)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Human')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
